// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMintSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMintSystem {
  function mint(uint32 item) external;
}
